version: "3.9"
services:
  cms:
    container_name: schranke_cms
    build:
      context: ./packages/cms
    ports:
      - 1337:1337
    volumes:
      - .tmp:/app/.tmp
  frontend:
    container_name: schranke_frontend
    build:
      context: ./packages/frontend
    ports:
      - 1338:1338
    depends_on:
      - cms
